# Site settings
title: Tounge In Geek News
header-img: img/home-bg.jpg
email: dev.centaurius@gmail.com
copyright_name: Jo D. Arias
description: "Light-hearted humor of a satirical nature!"
baseurl: ""
url: "http://toungeingeeknews.github.io/satire"
twitter_username:
github_username:
facebook_username:  
email_username: 

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
