# Site settings
title: Centaurius Blog
header-img: img/home-bg.jpg
email: dev.centaurius@gmail.com
copyright_name: Centaurius
description: "Centaurius Blog: A story of development, music and the ramblings on an engineering mind!"
baseurl: ""
url: "centaurius.github.io"
twitter_username: bleedin_orange
github_username:  centaurius
facebook_username:  
email_username: 

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
